### PR TITLE
fix: Use require.resolve to find resq

### PR DESCRIPTION
**Pull request by nickpalmer**
Referencing the path directly causes issues in projects using yarn
workspaces, which may install resq in a different location.

Additionally, the direct path inclusion makes this project dependent on
internal implementation details of resq, which are subject to change.

### CODE REVIEW

**Comment by abhinaba-ghosh** [comment]
hi @nickpalmer , thanks for raising this PR. The automated tests were not configured before to run in this PR./ Now I have configured that in `CircxleCI`. So, can you push a small commit, so that it triggered the run. This is just to validate the change. I hope, you will understand. 

Note, I tried this change couple of weeks ago, but could not able to find a good solution. Reference: https://github.com/abhinaba-ghosh/cypress-react-selector/issues/55

**Comment by baruchvlz** [comment]
@abhinaba-ghosh I think you can close and reopen the PR and it will trigger the CI.

**Comment by abhinaba-ghosh** [comment]
Hey, the good thing is all tests passed. That passed for me to0 weeks back but after releasing the version, `require.resolve` was throwing an error. 

@bahmutov Can you please help here understand what causes the problem in the released version?  Reference: https://github.com/abhinaba-ghosh/cypress-react-selector/issues/55

**Comment by bahmutov** [comment]
Does this fix work inside `cypress-react-unit-test`?

**Comment by abhinaba-ghosh** [comment]
> Does this fix work inside `cypress-react-unit-test`?

**Comment by abhinaba-ghosh** [comment]
@bahmutov Just checked. Seems the fix is working in `cypress-react-unit-test`

**Comment by bahmutov** [comment]
ok, great!

**Review by abhinaba-ghosh — APPROVED** [review]

**Comment by abhinaba-ghosh** [comment]
available in `v2.2.1`

**Pull request merged**
