### PR TITLE
Add retry and timeout to query

### PR DESCRIPTION
**Pull request by tobloef**
This PR adds the ability to retry finding a React element, as well as a timeout in case it couldn't be found. Cypress normally does this as well, but since this module uses resq it needs to be done manually. It is quite crucial for testing pages with for example short loading spinners before showing the main content, etc. The default Cypress timeout is used, so it should function how a user might expect. I'm not sure about how often to retry finding the element. Currently, it's set to 250ms, but there might be a better interval. Also, maybe there should be an option to disable the retry.

Let me know what you think.

### CODE REVIEW

**Comment by abhinaba-ghosh** [comment]
Hi @tobloef , retry ability is already added in the new version. For notes, the folder structure has changed quite a bit. Please verify the new version available.

**Comment by abhinaba-ghosh** [comment]
For reference: https://github.com/bahmutov/cypress-react-unit-test/issues/379

**Comment by tobloef** [comment]
> Hi @tobloef , retry ability is already added in the new version.

Ah, I can see that. We will try the new version then. Thanks!

**Comment by abhinaba-ghosh** [comment]
It will be a breaking change though. here is the [changelog](https://github.com/abhinaba-ghosh/cypress-react-selector/blob/master/CHANGELOG.md)

**Comment by tobloef** [comment]
We updated to the newest version quite painlessly, following the notes in the changelog 👍

**Comment by abhinaba-ghosh** [comment]
Hey, good to hear that. 
Now you can choose to [support](patreon.com/user?u=32109749) the project. It is completely optional :)

**Pull request closed without merging**
